### ISSUE TITLE
Pre-launch operation checklist

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1177]
# Fuzzer improvements 

+ [ ] Test fuzzer + prod
+ [ ] More varying file sizes
+ [ ] Don't waste time on checking things like the fuzzer does

# Backups

+ [ ] Test backups
+ [ ] Test PD
+ [ ] Operator security checkup

**Comment by Parth** [comment]
largely dupe: #1094
