### ISSUE TITLE
focus tracker

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2786]
editor focus issues:
- [x] https://github.com/lockbook/lockbook/issues/2663
- [x] https://github.com/lockbook/lockbook/issues/2726

editor focus conflicts with other egui widgets:
- [x] https://github.com/lockbook/lockbook/issues/2725
- [x] https://github.com/lockbook/lockbook/issues/2583
- [x] https://github.com/lockbook/lockbook/issues/2782

**Comment by tvanderstad** [comment]
split remaining issues to https://github.com/lockbook/lockbook/issues/2905
