### ISSUE TITLE
native focus tracker

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2905]
- [ ] https://github.com/lockbook/lockbook/issues/2388
- [ ] https://github.com/lockbook/lockbook/issues/2673
- [ ] https://github.com/lockbook/lockbook/issues/2462
