### ISSUE TITLE
man page and completion files

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#878]

**Comment by ad-tra** [comment]
# Roadmap
- [ ] research a clean way to implement completions on empty state 
- [ ] research a way to truncate completions paths to one level.
 - ex: `/lockbook/marketing/foo` => `foo`
- [ ] support fish  
- [ ] integrate static completions with dynamic  
- [ ] complete paths by id 
- [ ] complete username on share
